### ISSUE TITLE
Update for latest OpenJDK 8?

### ISSUE THREAD

**Issue by jschneider** [vjuranek/openJDK-native-plugin#1]
Hi guys,

any chance to see a new release that is able to install OpenJDK 8?

Thanks,

Johannes

**Comment by vjuranek** [comment]
Added in release 1.1 (released few minutes ago)

**Comment by jschneider** [comment]
Great. Thanks.

**Comment by vjuranek** [comment]
Please note, that there could be some issues with OpenJDK8 (IMHO same issue could happen also with previous OpenJDKs, but I spot it when testing OpenJDK8), logged as #2 and #3. Hopefully I'll fix these issues soon.
